### PR TITLE
Bump styled-components version

### PR DESCRIPTION
**Pull request by jameskraus**
Maybe bump the version with this too? Idk, it's not my repo. Mainly sending this PR since my flow check was failing with the old styled-components.

### CODE REVIEW

**Comment by jameskraus** [comment]
Tests passed on my macbook 

image

**Comment by derrickpelletier** [comment]
Hey sorry that I missed this, can you resolve the conflict and then I'll merge!

**Comment by jameskraus** [comment]
Hey, resolved the conflict

**Comment by derrickpelletier** [comment]
Thanks!

**Pull request merged**
